---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-gateway
  template:
    metadata:
      labels:
        app: order-gateway
    spec:
      containers:
        - name: order-gateway
          image: {{.Values.order_gateway.image}}
